services:
  routerb:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    environment:
      ROUTERB_ADDR: ':8080'
    restart: unless-stopped
    ports:
      - '127.0.0.1:8080:8080'
